{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foundry.fullname" . }}
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
spec:
  accessModes:
    {{ .Values.persistence.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 128Gi
  phase: Bound

{{- end }}
