apiVersion: v1
kind: Service
metadata:
  name: {{ include "foundry.fullname" . }}
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 3724
      targetPort: 3724
      protocol: UDP
      name: game1
    - port: 27015
      targetPort: 27015
      protocol: UDP
      name: game2
  selector:
    {{- include "foundry.selectorLabels" . | nindent 4 }}
