apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simbruna.fullname" . }}-api
  labels:
    {{- include "simbruna.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simbruna.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simbruna.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simbruna.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-pg-credentials
                  key: connection-string
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-oauth-secrets
                  key: client-id
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-oauth-secrets
                  key: client-secret
            - name: OAUTH_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-oauth-secrets
                  key: redirect-url
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: api-key
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: auth-domain
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: project-id
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: storage-bucket
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: messaging-sender-id
            - name: FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: app-id
            - name: FIREBASE_VAPID_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: vapid-key
            - name: API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "simbruna.fullname" . }}-firebase-secrets
                  key: api-endpoint
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}