apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "simbruna.fullname" . }}-db-init
  labels:
    {{- include "simbruna.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "simbruna.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: postgres:16
        command:
        - /bin/bash
        - -c
        - |
          export PGPASSWORD="$POSTGRES_ADMIN_PASSWORD"
          echo "Initializing database and user..."
          psql -h "$POSTGRES_HOST" -U "$POSTGRES_ADMIN_USER" -v app_password="$APP_PASSWORD" -f /scripts/init.sql
          echo "Database initialization completed successfully"
        env:
        - name: POSTGRES_HOST
          value: "app-postgres-postgresql.apps.svc.cluster.local"
        - name: POSTGRES_ADMIN_USER
          value: "postgres"
        - name: POSTGRES_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-postgres-postgresql
              key: postgres-password
              optional: false
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "simbruna.fullname" . }}-pg-credentials
              key: app-password
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
      volumes:
      - name: init-scripts
        configMap:
          name: {{ include "simbruna.fullname" . }}-db-init