apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simbruna.fullname" . }}-firebase-secrets
  labels:
    {{- include "simbruna.labels" . | nindent 4 }}
    app.kubernetes.io/component: firebase
type: Opaque
data:
  api-key: {{ .Values.firebase_api_key | b64enc | quote }}
  auth-domain: {{ .Values.firebase_auth_domain | b64enc | quote }}
  project-id: {{ .Values.firebase_project_id | b64enc | quote }}
  storage-bucket: {{ .Values.firebase_storage_bucket | b64enc | quote }}
  messaging-sender-id: {{ .Values.firebase_messaging_sender_id | toString | b64enc | quote }}
  app-id: {{ .Values.firebase_app_id | b64enc | quote }}
  vapid-key: {{ .Values.firebase_vapid_key | b64enc | quote }}
  api-endpoint: {{ .Values.api_endpoint | b64enc | quote }}