apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simbruna.fullname" . }}-oauth-secrets
  labels:
    {{- include "simbruna.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth
type: Opaque
data:
  client-id: {{ .Values.oauth_client_id | b64enc | quote }}
  client-secret: {{ .Values.oauth_client_secret | b64enc | quote }}
  redirect-url: {{ .Values.oauth_redirect_url | b64enc | quote }}