apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simbruna.fullname" . }}-pg-credentials
  labels:
    {{- include "simbruna.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  connection-string: {{ .Values.postgres_connection_string | b64enc | quote }}
  app-password: {{ .Values.postgres_app_password | b64enc | quote }}
